Class ML.Model.BO.Executor.CubeSourceScoreRequest Extends (%Persistent, Ens.Request)
{

Property MLOperationName As %String;

Property CubeSourceRowID As %String;

Storage Default
{
<Data name="CubeSourceScoreRequestDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>MLOperationName</Value>
</Value>
<Value name="3">
<Value>CubeSourceRowID</Value>
</Value>
</Data>
<DataLocation>^ML.Model.BB7C2.CubeSourceSA428D</DataLocation>
<DefaultData>CubeSourceScoreRequestDefaultData</DefaultData>
<IdLocation>^ML.Model.BB7C2.CubeSourceSA428D</IdLocation>
<IndexLocation>^ML.Model.BB7C2.CubeSourceSA428I</IndexLocation>
<StreamLocation>^ML.Model.BB7C2.CubeSourceSA428S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
