Class IRISDemo.BO.EncounterUpdate.EncounterUpdateResponse Extends (%Persistent, Ens.Response)
{

Property Status As %String;
Storage Default
{
<Data name="EncounterUpdateResponseDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Status</Value>
</Value>
</Data>
<DataLocation>^IRISDemo.B9F2B.EncounterUpd906D</DataLocation>
<DefaultData>EncounterUpdateResponseDefaultData</DefaultData>
<IdLocation>^IRISDemo.B9F2B.EncounterUpd906D</IdLocation>
<IndexLocation>^IRISDemo.B9F2B.EncounterUpd906I</IndexLocation>
<StreamLocation>^IRISDemo.B9F2B.EncounterUpd906S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
