#!/bin/bash

set -e 

echo
echo "### HOOK - build environment:"
echo "   SOURCE_BRANCH  : $SOURCE_BRANCH"
echo "   SOURCE_COMMIT  : $SOURCE_COMMIT"
echo "   COMMIT_MSG     : $COMMIT_MSG"
echo "   DOCKER_REPO    : $DOCKER_REPO"
echo "   DOCKERFILE_PATH: $DOCKERFILE_PATH"
echo "   DOCKER_TAG     : $DOCKER_TAG"
echo "   IMAGE_NAME     : $IMAGE_NAME"

cd ./image-riskengine
echo "### HOOK - Generating Synthetic Patient Data For RRLACE Build"
./synthea-loader.sh
cd ..

echo
echo "### HOOK - building readmission risk service..."
docker build -t ${DOCKER_REPO}:risksrv-${DOCKER_TAG} ./image-risksrv

echo
echo "### HOOK - building RRLACE Service..."
docker build -t ${DOCKER_REPO}:riskengine-${DOCKER_TAG} ./image-riskengine

echo
echo "### HOOK - building hisDB..."
docker build -t ${DOCKER_REPO}:hisdb-${DOCKER_TAG} ./image-hisdb

echo
echo "### HOOK - building hisUI..."
docker build -t ${DOCKER_REPO}:hisui-${DOCKER_TAG} ./image-hisui