#!/bin/bash

set -e 

echo
echo "### HOOK - Pushing banking transactions service..."
docker push ${DOCKER_REPO}:readmission_readmissionrisksrv-${DOCKER_TAG}

echo
echo "### HOOK - Pushing RRLACE Service..."
docker push ${DOCKER_REPO}:readmission_RRLACESrv-${DOCKER_TAG}

echo
echo "### HOOK - Pushing hisDB..."
docker push ${DOCKER_REPO}:readmission_hisdb-${DOCKER_TAG}

echo
echo "### HOOK - Pushing hisUI..."
docker push${DOCKER_REPO}:readmission_hisui-${DOCKER_TAG}