#!/bin/bash

set -e

echo
echo "### HOOK - Pushing banking transactions service..."
docker push ${DOCKER_REPO}:risksrv-${DOCKER_TAG}

echo
echo "### HOOK - Pushing RRLACE Service..."
docker push ${DOCKER_REPO}:riskengine-${DOCKER_TAG}

echo
echo "### HOOK - Pushing hisDB..."
docker push ${DOCKER_REPO}:hisdb-${DOCKER_TAG}

echo
echo "### HOOK - Pushing hisUI..."
docker push ${DOCKER_REPO}:hisui-${DOCKER_TAG}
